// Phase 1 임시 픽스처 — 현재 정적 사이트의 hero.js HERO_DATA / hours.js HOURS_DATA /
// assets/data/*.json을 그대로 옮긴 하드코딩 상수. Phase 2에서 Supabase 조회로 교체되면
// 이 파일은 삭제된다. 배열 순서 = 화면 표시 순서(정렬 로직 없음, 원본과 동일).
import type { BusinessHourEntry, CardData, SiteProfile } from '@/types/profile.types'

export const SITE_PROFILE: SiteProfile = {
  name: '소윤호',
  imageUrl: '/images/propil_v1.avif',
  subtitle: 'GospelFix 대표 · AI Agent 자동화 솔루션',
  company: 'GospelFix',
  companyEn: 'AI AGENT AUTOMATION',
  roleLines: ['가스펄픽스(GospelFix) 대표'],
  tags: ['AI 챗봇 예약 시스템', '1:1 문의', '온라인 서비스', '홈페이지', '쇼핑몰'],
  email: 'thdbsgh3443@kakao.com',
  phone: '010-3388-2024',
  phoneHref: 'tel:010-3388-2024',
  homepageUrl: 'https://gospelfix.vercel.app/layer',
}

export const BUSINESS_HOURS: BusinessHourEntry[] = [
  { day: 1, label: '월요일', open: '09:00', close: '22:30' },
  { day: 2, label: '화요일', open: '09:00', close: '22:30' },
  { day: 3, label: '수요일', open: '09:00', close: '22:30' },
  { day: 4, label: '목요일', open: '09:00', close: '22:30' },
  { day: 5, label: '금요일', open: null, close: null },
  { day: 6, label: '토요일', open: '09:00', close: '14:00' },
  { day: 0, label: '일요일', open: null, close: null },
]

export const PORTFOLIO_CARDS: CardData[] = [
  {
    id: 3,
    title: '고품격대패',
    titleSuffix: '',
    subtitle: '대패의 격이 다르다',
    date: '',
    info: '고품격대패 공식 웹사이트',
    link: 'https://xn--i89a2dz9q2p1bhpb.com/',
    tags: ['프랜차이즈', '외식업'],
    imageType: 'image',
    imageUrl: '/images/portfolio/gopoomgyeok.avif',
    unavailable: false,
    unavailableMessage: null,
  },
  {
    id: 2,
    title: '예작음악신문사',
    titleSuffix: '',
    subtitle: '무대가 가장 좋은 스승이다.',
    date: '',
    info: '예작음악신문사 공식 웹사이트',
    link: 'http://yezakeumak.com',
    tags: ['음악', '신문사'],
    imageType: 'image',
    imageUrl: '/images/portfolio/yezakeumak.avif',
    unavailable: true,
    unavailableMessage: '계약이 만료되어 더 이상 운영하지 않습니다.',
  },
  {
    id: 1,
    title: 'Dear Tint Santa',
    titleSuffix: '',
    subtitle: '크리스마스 감성을 담은 브랜드',
    date: '',
    info: 'Dear Tint Santa 공식 스토어',
    link: 'https://deartintsanta.com',
    tags: ['브랜드', '쇼핑몰'],
    imageType: 'image',
    imageUrl: '/images/portfolio/deartintsanta.avif',
    unavailable: false,
    unavailableMessage: null,
  },
]

export const MINISTRY_CARDS: CardData[] = [
  {
    id: 4,
    title: '홀리윈 2026',
    titleSuffix: '',
    subtitle: '전도 대상자 기도',
    date: '2026.10.24 (토)',
    info: '전도 대상자를 등록하고 함께 기도해요',
    link: 'https://gbc-sys.github.io/holy.win.2026/',
    tags: ['홀리윈', '전도'],
    imageType: 'image',
    imageUrl: '/images/portfolio/holywin.avif',
    unavailable: false,
    unavailableMessage: null,
  },
  {
    id: 3,
    title: '몽골 단기선교',
    titleSuffix: '',
    subtitle: '몽골 사역 프로젝트',
    date: '2026.06.28 - 07.04',
    info: '몽골 단기선교팀 소식과 기도 요청을 확인하세요',
    link: 'https://mongolia-employment.vercel.app/',
    tags: ['몽골', '단기선교'],
    imageType: 'image',
    imageUrl: '/images/portfolio/mongolia.avif',
    unavailable: false,
    unavailableMessage: null,
  },
  {
    id: 2,
    title: 'LOVE in Action',
    titleSuffix: '',
    subtitle: '강청 수련회',
    date: '2026.01.12 - 01.31',
    info: '강남중앙침례교회 청년부 온라인 서비스',
    link: 'https://gbc-sys.github.io/gangcheong/exaction',
    tags: ['수련회', '신청하기'],
    imageType: 'image',
    imageUrl: '/images/cards/thumbnail-1.png',
    unavailable: false,
    unavailableMessage: null,
  },
  {
    id: 1,
    title: '사랑의 언어 도장판',
    titleSuffix: '',
    subtitle: 'LOVE in Action',
    date: '2026.02.06 - 02.08',
    info: '5가지 사랑의 언어로 미션을 완료하세요',
    link: 'https://gbc-sys.github.io/gangcheong/mission',
    tags: ['미션', '도장판'],
    imageType: 'image',
    imageUrl: '/images/cards/thumbnail-2.png',
    unavailable: false,
    unavailableMessage: null,
  },
]
